# Generated by Django 2.1.5 on 2019-04-15 12:49

from django.db import migrations

from apps.energy_dashboard.models import DEFAULT_DASHBOARD_SCREEN_NAMES, DashboardScreen


def populate_screen_names(apps, schema_editor):
    model_class = apps.get_model('energy_dashboard', 'DashboardScreen')
    for name in DEFAULT_DASHBOARD_SCREEN_NAMES:
        model_class(name=name).save()


def remove_default_screen_names(apps, schema_editor):
    model_class = apps.get_model('energy_dashboard', 'DashboardScreen')
    for name in DEFAULT_DASHBOARD_SCREEN_NAMES:
        try:
            model_class.objects.get(name=name).delete()
        except DashboardScreen.DoesNotExist:
            continue


class Migration(migrations.Migration):
    dependencies = [
        ('energy_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_screen_names, remove_default_screen_names)
    ]
