# Generated by Django 2.1.5 on 2019-12-16 12:06

import apps.energy_dashboard.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_location_timezone'),
        ('energy_dashboard', '0002_auto_20190415_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', enumfields.fields.EnumField(enum=apps.energy_dashboard.models.DashboardType, max_length=40)),
                ('last_ping', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dashboardping',
            unique_together={('type', 'location')},
        ),
    ]
