# Generated by Django 2.1 on 2018-11-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_requests', '0002_auto_20180831_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='school_latitude',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='school_longitude',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
