# Generated by Django 2.1 on 2019-01-08 10:42

import django.db.models.deletion
from django.db import migrations, models

from apps.addresses.models import Address


def migrate_address_to_new_structure(apps, schema_editor):
    registration_request_class: apps.RegistrationRequest = apps.get_model('registration_requests',
                                                                          'RegistrationRequest')
    address_class: Address = apps.get_model('addresses', 'Address')

    for registration_request in registration_request_class.objects.all():
        registration_request.address = address_class.objects.create(
            line_1=registration_request.school_address,
            line_2=None,
            city=None,
            post_code=None,
            latitude=registration_request.school_latitude,
            longitude=registration_request.school_longitude,
        )
        registration_request.save()


class Migration(migrations.Migration):
    dependencies = [
        ('registration_requests', '0003_auto_20181106_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.Address'),
        ),
        migrations.RunPython(
            code=migrate_address_to_new_structure,
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='school_address',
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='school_latitude',
        ),
        migrations.RemoveField(
            model_name='registrationrequest',
            name='school_longitude',
        ),
    ]
