# Generated by Django 2.1.5 on 2019-01-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration_requests', '0005_auto_20190108_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
