# Generated by Django 2.1.4 on 2019-01-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration_requests', '0006_auto_20190109_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='electricity_provider',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='gas_provider',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
