# Generated by Django 2.1.4 on 2019-01-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_requests', '0007_auto_20190117_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='it_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it_manager_registration_request', to='registration_requests.ContactInformation'),
        ),
    ]
