# Generated by Django 2.1.4 on 2019-01-23 12:33

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration_requests', '0008_registrationrequest_it_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='company_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
