# Generated by Django 2.1.5 on 2019-01-23 13:39

from django.db import migrations, models

import apps.registration_requests.models
import utilities.custom_serializer_fields


class Migration(migrations.Migration):
    dependencies = [
        ('registration_requests', '0009_contactinformation_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationrequest',
            old_name='school_governor',
            new_name='legal_status',
        ),
        migrations.RunSQL('''
            UPDATE registration_requests_registrationrequest 
            SET legal_status = 'limited_company'
            WHERE legal_status = 'company' 
        '''),
        migrations.AddField(
            model_name='registrationrequest',
            name='is_school_agreement_signed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='governance_type',
            field=utilities.custom_serializer_fields.AutoLengthEnumField(
                enum=apps.registration_requests.models.GovernanceType, max_length=30, null=True),
        ),
        migrations.RunSQL('''            
            UPDATE registration_requests_registrationrequest 
            SET governance_type = 'other'
            WHERE governance_type = 'controlled_school';
            
            UPDATE registration_requests_registrationrequest 
            SET governance_type = 'local_authority_maintained'
            WHERE governance_type = 'maintained_school';
            
            UPDATE registration_requests_registrationrequest 
            SET governance_type = 'grammar_school'
            WHERE governance_type = 'voluntary_grammar';
            
            UPDATE registration_requests_registrationrequest 
            SET governance_type = 'independent_school'
            WHERE governance_type = 'school';
        '''),
    ]
