# Generated by Django 2.1.5 on 2019-01-23 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('registration_requests', '0010_auto_20190123_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationrequest',
            old_name='is_school_agreement_signed',
            new_name='is_school_agreement_accepted',
        ),
    ]
