# Generated by Django 2.1.5 on 2019-01-21 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration_requests', '0011_auto_20190123_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationrequest',
            old_name='reject_reason',
            new_name='registration_reject_reason',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='activation_reject_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='registered_school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='registration_request', to='locations.Location'),
        ),
    ]
