# Generated by Django 2.1.4 on 2019-01-17 11:01

import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
from django.db import migrations, models

import apps.registration_requests.models
import apps.registration_requests.types
import utilities.custom_serializer_fields


class Migration(migrations.Migration):
    dependencies = [
        ('registration_requests', '0012_auto_20190121_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('had_energy_audit', models.BooleanField()),
                ('want_energy_audit', models.BooleanField()),
                ('want_use_lessons_materials', models.BooleanField()),
                ('want_install_energy_monitoring', models.BooleanField()),
                ('want_participate_energy_management_interview', models.BooleanField()),
                ('signed_loa', private_storage.fields.PrivateFileField(null=True,
                                                                       storage=private_storage.storage.files.PrivateFileSystemStorage(),
                                                                       upload_to=apps.registration_requests.models.signed_loa_file_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='status',
            field=utilities.custom_serializer_fields.AutoLengthEnumField(default='trial_pending',
                                                                         enum=apps.registration_requests.types.Status,
                                                                         max_length=20),
        ),
        migrations.RunSQL('''
            UPDATE registration_requests_registrationrequest
            SET status = 'activation_accepted'
            WHERE status = 'ACCEPTED';
    
            UPDATE registration_requests_registrationrequest
            SET status = 'trial_rejected'
            WHERE status = 'REJECTED';
    
            UPDATE registration_requests_registrationrequest
            SET status = 'trial_pending'
            WHERE status = 'PENDING';
        '''),
        migrations.AddField(
            model_name='registrationrequest',
            name='questionnaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='registration_requests.Questionnaire'),
        ),
    ]
