# Generated by Django 2.1.5 on 2019-01-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('registration_requests', '0013_auto_20190117_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='allow_smart_dcc_data_access_to_third_party',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='use_artificial_benchmark_for_first_year',
            field=models.BooleanField(null=True),
        ),
    ]
