# Generated by Django 2.1.5 on 2019-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_requests', '0015_auto_20190712_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='used_renewable_energies',
            field=models.ManyToManyField(blank=True, to='registration_requests.RenewableEnergy'),
        ),
    ]
