# Generated by Django 2.1.5 on 2020-02-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_requests', '0017_auto_20200203_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name_plural': 'Contact information'},
        ),
        migrations.AlterModelOptions(
            name='renewableenergy',
            options={'verbose_name_plural': 'Renewable energies'},
        ),
    ]
