# Generated by Django 2.1 on 2018-11-07 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20181107_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='detailed_data_live_time',
            field=models.DurationField(default=datetime.timedelta(4), null=True),
        ),
    ]
