# Generated by Django 2.1 on 2018-11-12 10:34

import enumfields.fields
from django.db import migrations, models

import apps.resources.models
import apps.resources.types


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0003_auto_20181107_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_detailed_data_add_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='last_long_term_data_add_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='detailed_time_resolution',
            field=enumfields.fields.EnumField(enum=apps.resources.types.TimeResolution, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='long_term_time_resolution',
            field=enumfields.fields.EnumField(enum=apps.resources.types.TimeResolution, max_length=20, null=True),
        ),
    ]
