# Generated by Django 2.1 on 2018-11-23 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0004_auto_20181112_1034'),
    ]

    operations = [
        migrations.RunSQL("UPDATE resources_resource "
                          "SET detailed_time_resolution = 'second' "
                          "WHERE detailed_time_resolution = 'one_second'"),
        migrations.RunSQL("UPDATE resources_resource "
                          "SET long_term_time_resolution = 'second' "
                          "WHERE long_term_time_resolution = 'one_second'"),
    ]
