# Generated by Django 2.1 on 2018-11-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20181123_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('name',)},
        ),
    ]
