# Generated by Django 2.1 on 2018-12-11 13:46

import enumfields.fields
from django.db import migrations

import apps.resources.models
import apps.resources.types


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20181127_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='interpolation_type',
            field=enumfields.fields.EnumField(default='linear', enum=apps.resources.types.InterpolationType,
                                              max_length=10),
        ),
    ]
