# Generated by Django 2.1 on 2018-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resource_interpolation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='deleted',
            field=models.DateTimeField(db_column='deleted_at', editable=False, null=True),
        ),
    ]
