# Generated by Django 2.1.5 on 2019-01-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0008_resource_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_value',
            field=models.FloatField(null=True),
        ),
    ]
