# Generated by Django 2.1.5 on 2019-01-18 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0009_resource_last_value'),
    ]

    operations = [
        migrations.RunSQL('''
            DO $$
              DECLARE
                history_row historical_data_detailedhistoricaldata%ROWTYPE;
              BEGIN
                FOR history_row IN
                  (
                    SELECT history.id
                    FROM historical_data_longtermhistoricaldata AS history
                           JOIN resources_resource rr ON history.resource_id = rr.id
                    WHERE rr.long_term_time_resolution = 'half_hour'
                      AND rr.detailed_time_resolution IS NOT NULL
                    ORDER BY history.time
                  )
                  LOOP
                    UPDATE historical_data_longtermhistoricaldata
                    SET time = time - INTERVAL '30 minutes'
                    WHERE id = history_row.id;
                  END LOOP;
              END $$
        ''')
    ]
