# Generated by Django 2.2.28 on 2022-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_auto_20190527_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
