# Generated by Django 2.1 on 2018-11-06 17:02

from django.db import migrations, models
import django.db.models.deletion
import apps.energy_providers.providers.abstract
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energy_providers', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMeter',
            fields=[
                ('resource_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='energy_meter', serialize=False, to='resources.Resource')),
                ('meter_id', models.CharField(max_length=36)),
                ('type', enumfields.fields.EnumField(enum=apps.energy_providers.providers.abstract.MeterType, max_length=20)),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_meters', to='energy_providers.EnergyProviderAccount')),
            ],
            bases=('resources.resource',),
        ),
        migrations.AlterUniqueTogether(
            name='energymeter',
            unique_together={('meter_id', 'type', 'provider_account')},
        ),
    ]
