# Generated by Django 2.1 on 2018-11-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energymeter',
            options={'ordering': ('name',)},
        ),
    ]
