# Generated by Django 2.1.5 on 2022-01-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters', '0002_auto_20181127_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='energymeter',
            name='is_half_hour_meter',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
