# Generated by Django 2.1.5 on 2022-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters', '0003_energymeter_is_half_hour_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='energymeter',
            name='tariff_id',
            field=models.CharField(default=None, max_length=36, null=True),
        ),
    ]
