# Generated by Django 2.1.5 on 2022-02-03 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters', '0004_energymeter_tariff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energymeter',
            name='tariff_id',
        ),
        migrations.AddField(
            model_name='energymeter',
            name='minutes_delay',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
