# Generated by Django 2.1.5 on 2022-02-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters', '0005_auto_20220203_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='energymeter',
            name='live_values_meter',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hh_values_meter', to='energy_meters.EnergyMeter'),
        ),
    ]
