# Generated by Django 2.0.5 on 2018-07-04 18:20

from django.db import migrations, models
import utilities.alphanumeric


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='uuid',
        ),
        migrations.AddField(
            model_name='location',
            name='uid',
            field=models.CharField(db_index=True, default=utilities.alphanumeric.generate_alphanumeric, max_length=36, unique=True),
        ),
    ]
