# Generated by Django 2.1 on 2018-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_current_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='share_energy_consumption',
            field=models.BooleanField(default=True),
        ),
    ]
