# Generated by Django 2.1 on 2018-11-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20180831_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
