# Generated by Django 2.1 on 2018-11-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20181116_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=51.51),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=-0.13),
        ),
    ]
