# Generated by Django 2.1.5 on 2019-04-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_change_address_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='current_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='themes.Theme'),
        ),
    ]
