# Generated by Django 2.1.5 on 2019-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_auto_20190411_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='pupils_count',
            field=models.IntegerField(default=100),
        ),
    ]
