# Generated by Django 2.1.5 on 2019-04-25 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_location_pupils_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='pupils_count',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
