# Generated by Django 2.1.5 on 2020-02-03 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_location_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.Address'),
        ),
    ]
