# Generated by Django 2.1.5 on 2021-06-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_auto_20200203_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_energy_data_open',
            field=models.BooleanField(default=False),
        ),
    ]
