# Generated by Django 2.1 on 2018-10-25 10:28

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smart_things_web_hooks', '0001_initial'),
        ('locations', '0005_auto_20180831_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartThingsApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_auth_token', encrypted_model_fields.fields.EncryptedCharField()),
                ('refresh_token', encrypted_model_fields.fields.EncryptedCharField()),
                ('app_id', models.CharField(max_length=50)),
                ('app_location_id', models.CharField(max_length=50)),
                ('auth_token_updated_at', models.DateTimeField(auto_now_add=True)),
                ('refresh_token_updated_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='smart_things_web_hooks.SmartThingsConnector')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_things_apps', to='locations.Location')),
            ],
            options={
                'verbose_name': 'SmartThings App',
                'verbose_name_plural': 'SmartThings Apps',
            },
        ),
    ]
