# Generated by Django 2.1.5 on 2019-04-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_things_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartthingsapp',
            name='token_refresh_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
