# Generated by Django 2.1.5 on 2019-03-26 08:57

import apps.manuals.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualmediafile',
            name='type',
            field=enumfields.fields.EnumField(default='other', enum=apps.manuals.models.MediaFileType, max_length=12),
        ),
    ]
