# Generated by Django 2.1.5 on 2019-04-10 14:12
import uuid

from django.db import migrations, models
from django.utils.text import slugify


def set_slug_value(apps, schema_editor):
    model = apps.get_model('manuals', 'Manual')
    for manual in model.objects.all():
        manual.slug = slugify(manual.title)
        if model.objects.filter(slug=manual.slug).exists():
            manual.slug += f'-{str(uuid.uuid4())[:8]}'
        manual.save()


class Migration(migrations.Migration):
    dependencies = [
        ('manuals', '0003_auto_20190405_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.RunPython(set_slug_value, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='manual',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
