# Generated by Django 2.1.5 on 2019-04-12 14:34

import apps.manuals.models
from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0004_manual_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='avatar',
        ),
        migrations.AddField(
            model_name='manual',
            name='avatar_image',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=apps.manuals.models.manuals_avatars_file_path, verbose_name='Avatar image'),
        ),
        migrations.AddField(
            model_name='manual',
            name='avatar_video',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=apps.manuals.models.manuals_avatars_file_path, verbose_name='Avatar video'),
        ),
    ]
