# Generated by Django 2.1.5 on 2019-04-25 14:48

import apps.manuals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0006_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='avatar_image',
            field=models.FileField(blank=True, null=True, upload_to=apps.manuals.models.manuals_avatars_file_path, verbose_name='Avatar image'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='avatar_video',
            field=models.FileField(blank=True, null=True, upload_to=apps.manuals.models.manuals_avatars_file_path, verbose_name='Avatar video'),
        ),
        migrations.AlterField(
            model_name='manualmediafile',
            name='media_file',
            field=models.FileField(upload_to=apps.manuals.models.manuals_file_path, verbose_name='Media file'),
        ),
    ]
