# Generated by Django 2.1.5 on 2019-05-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0007_auto_20190425_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='manual',
            options={'ordering': ('category', 'priority', 'created_at')},
        ),
        migrations.AddField(
            model_name='manual',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manual',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuals', to='manuals.Category'),
        ),
        migrations.AlterField(
            model_name='manualmediafile',
            name='manual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='manuals.Manual'),
        ),
    ]
