# Generated by Django 2.1 on 2018-11-06 17:02

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import apps.smart_things_c2c.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energy_meters', '0001_initial'),
        ('smart_things_web_hooks', '0002_auto_20181026_0909'),
        ('smart_things_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2CDeviceToEnergyMeterMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(db_index=True, max_length=50)),
                ('device_label', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('type', enumfields.fields.EnumField(enum=apps.smart_things_c2c.models.DeviceType, max_length=20)),
                ('profile_id', models.CharField(max_length=50)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_profiles', to='smart_things_web_hooks.SmartThingsConnector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='c2cdevicetoenergymetermap',
            name='device_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_things_c2c.DeviceProfile'),
        ),
        migrations.AddField(
            model_name='c2cdevicetoenergymetermap',
            name='energy_meter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_things_c2c_mapper', to='energy_meters.EnergyMeter'),
        ),
        migrations.AddField(
            model_name='c2cdevicetoenergymetermap',
            name='smart_things_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_things_apps.SmartThingsApp'),
        ),
    ]
