# Generated by Django 2.1.5 on 2019-02-06 12:03

import django.db.models.deletion
from django.db import migrations, models

import apps.energy_meters_billing_info.models
import apps.energy_providers.providers.abstract
import utilities.custom_serializer_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('locations', '0010_change_address_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMeterBillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_type', utilities.custom_serializer_fields.AutoLengthEnumField(
                    enum=apps.energy_providers.providers.abstract.MeterType, max_length=20)),
                ('meter_type', utilities.custom_serializer_fields.AutoLengthEnumField(
                    enum=apps.energy_meters_billing_info.models.UsedMeterType, max_length=10)),
                ('meter_id', models.CharField(max_length=100)),
                ('annual_consumption', models.FloatField(null=True)),
                ('annual_money_spend', models.FloatField()),
                ('unit_rate', models.FloatField()),
                ('standing_charge', models.FloatField()),
                ('contract_ends_on', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='energymeterbillinginfo',
            unique_together={('location', 'meter_id')},
        ),
    ]
