# Generated by Django 2.1.5 on 2019-07-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0002_energymeterbillinginfo_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='energymeterbillinginfo',
            name='contract_starts_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='energymeterbillinginfo',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_meter_billing_info', to='resources.Resource'),
        ),
    ]
