# Generated by Django 2.1.5 on 2019-07-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0003_auto_20190703_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energymeterbillinginfo',
            name='resource',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_meter_billing_info', to='resources.Resource'),
        ),
    ]
