# Generated by Django 2.1.5 on 2019-07-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0004_auto_20190710_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='energymeterbillinginfo',
            name='supplier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
