# Generated by Django 2.1.5 on 2019-11-20 13:50

import apps.mug_service.constants
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utilities.custom_serializer_fields


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0006_auto_20191120_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMeterBillingInfoUnitRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_rate_period', utilities.custom_serializer_fields.AutoLengthEnumField(enum=apps.mug_service.constants.MUGMeterRatePeriod, max_length=20)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('energy_meter_billing_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_rates', to='energy_meters_billing_info.EnergyMeterBillingInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
