# Generated by Django 2.1.5 on 2019-11-26 11:31

import apps.mug_service.constants
from django.db import migrations
import utilities.custom_serializer_fields


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0008_unit_rate_to_EMBI_unit_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energymeterbillinginfounitrate',
            name='unit_rate_period',
            field=utilities.custom_serializer_fields.AutoLengthEnumField(default='Day', enum=apps.mug_service.constants.MUGMeterRatePeriod, max_length=20),
        ),
    ]
