# Generated by Django 2.1.5 on 2019-12-03 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0010_smart_amr_classic_to_smart_or_amr_non_amr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energymeterbillinginfounitrate',
            old_name='value',
            new_name='unit_rate',
        ),
        migrations.AddField(
            model_name='energymeterbillinginfounitrate',
            name='consumption',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.RenameModel('EnergyMeterBillingInfoUnitRate', 'EnergyMeterBillingInfoConsumption'),
        migrations.AlterField(
            model_name='energymeterbillinginfoconsumption',
            name='energy_meter_billing_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_by_rates',
                                    to='energy_meters_billing_info.EnergyMeterBillingInfo'),
        ),
    ]
