# Generated by Django 2.1.5 on 2019-12-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0011_auto_20191203_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energymeterbillinginfo',
            name='annual_consumption',
        ),
    ]
