# Generated by Django 2.1.5 on 2020-02-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0013_auto_20200203_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energymeterbillinginfo',
            options={'verbose_name_plural': 'Energy meter billing info'},
        ),
    ]
