# Generated by Django 2.1.5 on 2020-02-18 11:41

import apps.mug_service.constants
from django.db import migrations
import utilities.custom_serializer_fields


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0014_auto_20200204_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energymeterbillinginfo',
            name='unit_rate_type',
            field=utilities.custom_serializer_fields.AutoLengthEnumField(default='Single', enum=apps.mug_service.constants.MUGMeterRateTypes, max_length=40),
        ),
    ]
