# Generated by Django 2.1 on 2018-12-04 16:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import apps.lesson_plans.models
import private_storage.fields
import private_storage.storage.files
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0009_auto_20181116_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=512)),
                ('content', tinymce.models.HTMLField()),
                ('plan_material', private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=apps.lesson_plans.models.lesson_plan_file_path, verbose_name='File')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lessonplan',
            unique_together={('session_number', 'location')},
        ),
    ]
