# Generated by Django 2.1 on 2018-12-07 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='session_number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='lessonplan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='location',
        ),
    ]
