# Generated by Django 2.1.5 on 2019-08-22 13:54

import apps.lesson_plans.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0002_auto_20181207_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuccessCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='duration',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='key_information',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='lesson_avatar',
            field=models.FileField(blank=True, null=True, upload_to=apps.lesson_plans.models.lesson_avatar_file_path, verbose_name='Lesson avatar'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='lesson_topics',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='overview',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='successcriteria',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_criteria', to='lesson_plans.LessonPlan'),
        ),
        migrations.AddField(
            model_name='lessonobjective',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_objectives', to='lesson_plans.LessonPlan'),
        ),
    ]
