# Generated by Django 2.1.5 on 2019-08-23 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0005_auto_20190823_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='session_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
