# Generated by Django 2.1.5 on 2019-08-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0006_auto_20190823_1513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonplan',
            unique_together={('session_number', 'lesson_group')},
        ),
    ]
