# Generated by Django 2.1.5 on 2019-08-30 09:24

import apps.lesson_plans.models
from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0007_auto_20190827_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='plan_material',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=apps.lesson_plans.models.lesson_plan_file_path, verbose_name='File'),
        ),
    ]
