# Generated by Django 2.1.5 on 2019-09-02 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0008_auto_20190830_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='numeration_prefix',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='lessonplan',
            unique_together={('session_number', 'lesson_group', 'numeration_prefix')},
        ),
    ]
