# Generated by Django 2.1.5 on 2019-09-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0009_auto_20190902_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonobjective',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='successcriteria',
            options={'ordering': ['id']},
        ),
    ]
