# Generated by Django 2.1.5 on 2019-09-03 09:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0010_auto_20190902_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='key_information',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='overview',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
