# Generated by Django 2.1.5 on 2019-09-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0011_auto_20190903_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='numeration_prefix_label',
            field=models.CharField(default='lesson', max_length=32),
        ),
    ]
