# Generated by Django 2.1.5 on 2019-09-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0012_lessonplan_numeration_prefix_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='lesson_label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lessonplan',
            unique_together={('session_number', 'lesson_group')},
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='numeration_prefix',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='numeration_prefix_label',
        ),
    ]
