# Generated by Django 2.1.5 on 2021-05-11 17:34

import apps.lesson_plans.models
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0014_lessongroup_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('plan_material', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=apps.lesson_plans.models.lesson_plan_file_path, verbose_name='File')),
                ('lesson_avatar', models.FileField(blank=True, null=True, upload_to=apps.lesson_plans.models.lesson_avatar_file_path, verbose_name='Lesson avatar')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lessongroup',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lessonplannew',
            name='lesson_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lesson_plans.LessonGroup'),
        ),
    ]
