# Generated by Django 2.1.5 on 2021-05-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0015_auto_20210511_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplannew',
            name='lesson_avatar',
        ),
        migrations.AlterField(
            model_name='lessonplannew',
            name='lesson_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='lesson_plans.LessonGroup'),
        ),
    ]
