# Generated by Django 2.1.5 on 2021-06-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0016_auto_20210512_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplannew',
            options={'ordering': ['title']},
        ),
    ]
