# Generated by Django 2.2.28 on 2022-04-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0017_auto_20210617_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessongroup',
            name='group_avatar',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='lessongroup',
            name='materials',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='lesson_avatar',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='plan_material',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplannew',
            name='plan_material',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
