# Generated by Django 2.1 on 2018-09-14 19:11

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import apps.notifications.models.notification_target
import apps.notifications.models.notification_triggers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0005_auto_20180831_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_time', models.DateTimeField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', enumfields.fields.EnumField(enum=apps.notifications.models.notification_target.DestinationType, max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.notifications.models.notification_triggers.ParentModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', enumfields.fields.EnumField(enum=apps.notifications.models.notification_triggers.TriggerType, max_length=30)),
                ('max_notification_frequency', enumfields.fields.EnumField(enum=apps.notifications.models.notification_triggers.MaxNotifyFrequency, max_length=30)),
                ('active_time_range_start', models.TimeField(null=True)),
                ('active_time_range_end', models.TimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.notifications.models.notification_triggers.ParentModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DailyUsageTrigger',
            fields=[
                ('base_trigger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='daily_usage', serialize=False, to='notifications.NotificationTrigger')),
                ('threshold_in_percents', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.notificationtrigger',),
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('base_target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='email_notification', serialize=False, to='notifications.NotificationTarget')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.notificationtarget',),
        ),
        migrations.CreateModel(
            name='SmsNotification',
            fields=[
                ('base_target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sms_notification', serialize=False, to='notifications.NotificationTarget')),
                ('number', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.notificationtarget',),
        ),
        migrations.CreateModel(
            name='ValueLevelTrigger',
            fields=[
                ('base_trigger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='value_level', serialize=False, to='notifications.NotificationTrigger')),
                ('condition', enumfields.fields.EnumField(enum=apps.notifications.models.notification_triggers.Condition, max_length=10)),
                ('argument', models.FloatField()),
                ('min_duration', models.DurationField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.notificationtrigger',),
        ),
        migrations.AddField(
            model_name='notificationtrigger',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='notificationtrigger',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_for_triggers', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='notificationtarget',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_targets', to='notifications.NotificationTrigger'),
        ),
        migrations.AddField(
            model_name='notificationeventlog',
            name='notification_trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_events', to='notifications.NotificationTrigger'),
        ),
    ]
