# Generated by Django 2.1 on 2018-10-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtrigger',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
