# Generated by Django 2.1 on 2018-10-04 13:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationtrigger_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationeventlog',
            name='notification_trigger',
        ),
        migrations.AddField(
            model_name='notificationeventlog',
            name='location_uid',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationeventlog',
            name='trigger_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
