# Generated by Django 2.1 on 2018-10-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationtrigger_active_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtrigger',
            name='last_action_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
