# Generated by Django 2.1 on 2018-11-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0004_auto_20181112_1034'),
        ('notifications', '0005_notificationtrigger_last_action_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtrigger',
            name='source_resource',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='source_for_triggers', to='resources.Resource'),
        ),
        migrations.AlterField(
            model_name='notificationtrigger',
            name='source_location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='source_for_triggers', to='locations.Location'),
        ),
    ]
