# Generated by Django 2.1 on 2018-11-21 11:38

import django.db.models.deletion
from django.db import migrations, models


def remove_all_rows(apps, schema_editor):
    notification_event_log_class = apps.get_model('notifications', 'NotificationEventLog')
    notification_event_log_class.objects.using(schema_editor.connection.alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('locations', '0009_auto_20181116_1358'),
        ('notifications', '0006_auto_20181113_1227'),
    ]

    operations = [
        migrations.RunPython(remove_all_rows),
        migrations.RemoveField(
            model_name='notificationeventlog',
            name='location_uid',
        ),
        migrations.AddField(
            model_name='notificationeventlog',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
            preserve_default=False,
        ),
    ]
