# Generated by Django 2.1.5 on 2019-12-04 15:25

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields

from apps.notifications.models.notification_triggers import AbnormalValueTriggerType
import apps.notifications.types


def create_default_abnormal_value_triggers(apps, _):
    trigger = apps.get_model('notifications', 'AbnormalValueTrigger')
    for trigger_type in list(AbnormalValueTriggerType):
        trigger.objects.create(
            type=trigger_type,
            abnormal_max_value=trigger_type.abnormal_max_value,
            abnormal_min_value=trigger_type.abnormal_min_value
        )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20181121_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalValueTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', enumfields.fields.EnumField(enum=apps.notifications.types.AbnormalValueTriggerType, max_length=20, unique=True)),
                ('abnormal_max_value', models.FloatField()),
                ('abnormal_min_value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotificationEventLog',
            fields=[
                ('notificationeventlog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.NotificationEventLog')),
                ('status', enumfields.fields.EnumField(default='active', enum=apps.notifications.types.NotificationStatus, max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('notifications.notificationeventlog',),
        ),
        migrations.RunPython(create_default_abnormal_value_triggers, migrations.RunPython.noop)
    ]
