# Generated by Django 2.2.28 on 2022-04-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_dailyreportsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmsNotification',
        ),
    ]
