# Generated by Django 2.0.5 on 2018-07-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('uid', models.CharField(max_length=36, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubs', to='locations.Location')),
            ],
            options={
                'verbose_name': 'Raspberry Hub',
                'verbose_name_plural': 'Raspberry Hubs',
                'default_permissions': ('add', 'change', 'delete', 'retrieve'),
            },
        ),
    ]
