# Generated by Django 2.0.5 on 2018-07-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberryhub',
            name='uid',
            field=models.CharField(db_index=True, max_length=36, unique=True),
        ),
    ]
