# Generated by Django 2.0.5 on 2018-07-13 11:26

from django.db import migrations, models
import utilities.alphanumeric


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0002_auto_20180704_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberryhub',
            name='uid',
            field=models.CharField(db_index=True, default=utilities.alphanumeric.generate_alphanumeric, max_length=36, unique=True),
        ),
    ]
