# Generated by Django 2.1 on 2018-08-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_auto_20180713_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raspberryhub',
            options={'verbose_name': 'Raspberry Hub', 'verbose_name_plural': 'Raspberry Hubs'},
        ),
    ]
