# Generated by Django 2.1.5 on 2019-01-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hubs', '0006_auto_20181210_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberryhub',
            name='deleted',
            field=models.DateTimeField(db_column='deleted_at', editable=False, null=True),
        ),
    ]
