# Generated by Django 2.1.5 on 2019-03-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_change_address_structure'),
        ('microbit_historical_data', '0001_initial'),
        ('microbit_variables', '0004_auto_20180911_1038'),
        ('hubs', '0007_raspberryhub_deleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaspberryHub',
            new_name='Hub',
        ),
        migrations.AlterModelOptions(
            name='hub',
            options={'verbose_name': 'Hub', 'verbose_name_plural': 'Hubs'},
        ),
    ]
