# Generated by Django 2.1.5 on 2019-03-11 13:46

import apps.hubs.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0008_auto_20190311_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='type',
            field=enumfields.fields.EnumField(default='raspberry', enum=apps.hubs.models.HubType, max_length=10),
        ),
    ]
