# Generated by Django 2.2.28 on 2022-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0009_hub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
