# Generated by Django 2.1 on 2018-08-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={},
        ),
    ]
