# Generated by Django 2.1 on 2018-11-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0005_auto_20180831_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartThingsDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('smart_things_id', models.CharField(db_index=True, max_length=50)),
                ('smart_things_location', models.CharField(max_length=50)),
                ('sub_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_things_devices', to='locations.Location')),
            ],
            options={
                'verbose_name': 'Smart Device',
                'verbose_name_plural': 'Smart Devices',
            },
        ),
        migrations.AlterUniqueTogether(
            name='smartthingsdevice',
            unique_together={('smart_things_id', 'sub_location')},
        ),
    ]
