# Generated by Django 2.1 on 2018-12-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_things_devices', '0003_auto_20181212_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartthingsdevice',
            name='smart_things_id',
            field=models.CharField(db_index=True, editable=False, max_length=50),
        ),
    ]
