# Generated by Django 2.1 on 2018-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_things_devices', '0004_auto_20181214_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartthingsdevice',
            name='deleted',
            field=models.DateTimeField(db_column='deleted_at', editable=False, null=True),
        ),
    ]
