# Generated by Django 2.1.5 on 2019-03-26 13:09

import apps.smart_things_devices.types
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smart_things_devices', '0006_auto_20190124_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartthingsdevice',
            name='status',
            field=enumfields.fields.EnumField(default='UNKNOWN', enum=apps.smart_things_devices.types.DeviceStatus, max_length=10),
        ),
        migrations.AddField(
            model_name='smartthingsdevice',
            name='status_updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
