# Generated by Django 2.1.5 on 2019-04-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_things_devices', '0007_auto_20190326_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartthingsdevice',
            name='room_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
