# Generated by Django 2.1.5 on 2019-12-12 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_things_devices', '0008_smartthingsdevice_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartthingsdevice',
            name='battery_health',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
