# Generated by Django 2.0.5 on 2018-07-02 17:31

import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import apps.microbit_variables.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrobitVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('value', models.CharField(max_length=15)),
                ('shared_with', enumfields.fields.EnumField(blank=True, default='', enum=apps.microbit_variables.models.ShareType, max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='locations.Location')),
                ('raspberry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='hubs.RaspberryHub')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
                'default_permissions': ('add', 'change', 'delete', 'retrieve'),
            },
        ),
    ]
