# Generated by Django 2.0.5 on 2018-07-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('microbit_variables', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='microbitvariable',
            unique_together={('name', 'location')},
        ),
    ]
