# Generated by Django 2.1 on 2018-08-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microbit_variables', '0002_auto_20180705_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microbitvariable',
            options={'verbose_name': 'Variable', 'verbose_name_plural': 'Variables'},
        ),
    ]
