# Generated by Django 2.1 on 2018-09-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20180831_1602'),
        ('microbit_variables', '0003_auto_20180831_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microbitvariable',
            old_name='name',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='microbitvariable',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='microbitvariable',
            unique_together={('key', 'location')},
        ),
    ]
