# Generated by Django 2.1 on 2018-10-24 19:13

from django.db import migrations, models
import encrypted_model_fields.fields
import enumfields.fields
import apps.smart_things_web_hooks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartThingsConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', enumfields.fields.EnumField(default='smart_app', enum=apps.smart_things_web_hooks.models.SmartThingsConnectorType, max_length=20)),
                ('connector_id', models.CharField(max_length=36, unique=True)),
                ('connector_secret', encrypted_model_fields.fields.EncryptedCharField()),
                ('connector_public_key', encrypted_model_fields.fields.EncryptedTextField()),
            ],
            options={
                'verbose_name': 'Smart Things Connector',
                'verbose_name_plural': 'Smart Things Connectors',
            },
        ),
    ]
