# Generated by Django 2.1 on 2018-10-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_things_web_hooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartthingsconnector',
            old_name='name',
            new_name='connector_name',
        ),
    ]
