# Generated by Django 2.1 on 2018-12-14 13:57

import django.db.models.deletion
from django.db import migrations, models

import apps.smart_things_devices.types
import utilities.custom_serializer_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0007_resource_interpolation_type'),
        ('smart_things_devices', '0004_auto_20181214_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartThingsSensor',
            fields=[
                ('resource_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='smart_things_sensor', serialize=False, to='resources.Resource')),
                ('capability', utilities.custom_serializer_fields.AutoLengthEnumField(db_index=True, editable=False, enum=apps.smart_things_devices.types.Capability, max_length=20)),
                ('events_subscription_id', models.CharField(max_length=50, null=True)),
                ('device', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='smart_things_devices.SmartThingsDevice')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=('resources.resource',),
        ),
        migrations.AlterUniqueTogether(
            name='smartthingssensor',
            unique_together={('device', 'capability')},
        ),
    ]
