# Generated by Django 2.1 on 2018-12-14 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('smart_things_sensors', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('''                
        DO $$
          BEGIN
            IF EXISTS(SELECT *
                      FROM information_schema.tables
                      WHERE table_name = 'smart_things_temperature_meters_smartthingstemperaturemeter') THEN
              INSERT INTO smart_things_sensors_smartthingssensor (resource_ptr_id, capability, events_subscription_id,
                                                                  device_id)
              SELECT resource_ptr_id, 'temperature' as capability, NULL as events_subscription_id, device_id
              FROM smart_things_temperature_meters_smartthingstemperaturemeter;
              
            END IF;
          END $$;
        ''')
    ]
