# Generated by Django 2.1 on 2018-12-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_things_sensors', '0004_auto_20181226_1715'),
    ]

    operations = [
        migrations.RunSQL("UPDATE smart_things_sensors_smartthingssensor "
                          "SET capability = 'temperatureMeasurement' "
                          "WHERE capability = 'temperature' "),
    ]
