# Generated by Django 2.1.5 on 2019-12-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_things_sensors', '0006_smartthingsenergymeter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartthingssensor',
            name='events_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
