# Generated by Django 2.1.5 on 2019-12-12 10:21

from django.db import migrations


def make_st_energy_meters_push_supported(apps, schema_editor):
    SmartThingsEnergyMeter = apps.get_model('smart_things_sensors', 'SmartThingsEnergyMeter')
    db_alias = schema_editor.connection.alias

    SmartThingsEnergyMeter.objects.using(db_alias).update(
        preferred_data_collection_method='push',
        supported_data_collection_methods=['pull', 'push']
    )


def make_st_energy_meters_pull_supported(apps, schema_editor):
    SmartThingsEnergyMeter = apps.get_model('smart_things_sensors', 'SmartThingsEnergyMeter')
    db_alias = schema_editor.connection.alias

    SmartThingsEnergyMeter.objects.using(db_alias).update(
        preferred_data_collection_method='pull',
        supported_data_collection_methods=['pull']
    )


class Migration(migrations.Migration):

    dependencies = [
        ('smart_things_sensors', '0008_auto_20191209_1930'),
    ]

    operations = [
        migrations.RunPython(make_st_energy_meters_push_supported, make_st_energy_meters_pull_supported),
    ]
