# Generated by Django 2.1 on 2018-09-11 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0005_auto_20180831_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_days', to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
