# Generated by Django 2.1.5 on 2019-04-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration_requests', '0014_auto_20190129_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mug_customer_id', models.PositiveIntegerField()),
                ('registration_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mug_customer', to='registration_requests.RegistrationRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
