# Generated by Django 2.1.5 on 2019-04-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_change_address_structure'),
        ('mug_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mug_site_id', models.PositiveIntegerField()),
                ('sub_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mug_site', to='locations.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
