# Generated by Django 2.1.5 on 2019-04-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0001_initial'),
        ('mug_service', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mug_meter_id', models.PositiveIntegerField()),
                ('energy_meter_billing_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mug_meter', to='energy_meters_billing_info.EnergyMeterBillingInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
