# Generated by Django 2.1.5 on 2019-09-12 12:17

import apps.mug_service.internal_types
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0005_energymeterbillinginfo_supplier_id'),
        ('mug_service', '0003_meter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_id', models.PositiveIntegerField(unique=True)),
                ('quote_id', models.PositiveIntegerField(unique=True)),
                ('from_supplier_id', models.PositiveIntegerField()),
                ('to_supplier_id', models.PositiveIntegerField()),
                ('to_tariff_name', models.CharField(max_length=100)),
                ('status', enumfields.fields.EnumField(enum=apps.mug_service.constants.SwitchStatus, max_length=40)),
                ('energy_meter_billing_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='energy_meters_billing_info.EnergyMeterBillingInfo')),
            ],
            options={
                'verbose_name_plural': 'switches',
            },
        ),
    ]
