# Generated by Django 2.1.5 on 2019-12-25 15:53

from datetime import date

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mug_service', '0004_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='contract_end_date',
            field=models.DateField(default=date.today),
        ),
        migrations.AddField(
            model_name='switch',
            name='contract_start_date',
            field=models.DateField(default=date.today),
        ),
        migrations.AddField(
            model_name='switch',
            name='to_day_unit_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='switch',
            name='to_evening_and_weekend_unit_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='switch',
            name='to_night_unit_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='switch',
            name='to_standing_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='switch',
            name='contract_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='switch',
            name='contract_end_date',
            field=models.DateField(),
        ),
    ]
