# Generated by Django 2.1.5 on 2022-01-28 10:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mug_service', '0006_switch_to_peak_unit_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('battery_capacity', models.IntegerField(default=0)),
                ('calculation_date', models.CharField(default=0, max_length=50)),
                ('charging_hours', models.IntegerField(default=1)),
                ('charging_start_time', models.TimeField(default=django.utils.timezone.now)),
                ('cumulative_battery_savings', models.FloatField(default=0.0)),
                ('cumulative_solar_savings', models.FloatField(default=0.0)),
                ('current_battery_capacity', models.FloatField(default=0.0)),
                ('daily_battery_savings', models.FloatField(default=0.0)),
                ('daily_solar_savings', models.FloatField(default=0.0)),
                ('discharging_hours', models.IntegerField(default=1)),
                ('discharging_start_time', models.TimeField(default=django.utils.timezone.now)),
                ('is_battery_physical', models.BooleanField(default=False)),
                ('is_solar', models.BooleanField(default=False)),
                ('solar_capacity', models.IntegerField(default=0)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mug_service.Meter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
