# Generated by Django 2.1.5 on 2022-02-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mug_service', '0007_savings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculation_date', models.CharField(default='', max_length=50)),
                ('charging_carbon_intensity', models.IntegerField(default=0)),
                ('discharging_carbon_intensity', models.IntegerField(default=0)),
                ('daily_net_carbon_intensity', models.IntegerField(default=0)),
                ('cumulative_net_carbon_intensity', models.IntegerField(default=0)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mug_service.Meter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
