# Generated by Django 2.1.4 on 2019-01-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
