# Generated by Django 2.0.5 on 2018-07-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_version',
            field=models.IntegerField(default=1),
        ),
    ]
