# Generated by Django 2.0.5 on 2018-07-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_password_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ('add', 'change', 'delete', 'retrieve'), 'permissions': (('manage_sme_admins', 'Can manage SME admins'), ('manage_teachers', 'Can manage teachers'), ('manage_pupils', 'Can manage pupils'), ('manage_energy_screen', 'Can manage energy screen')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
