# Generated by Django 2.1 on 2018-12-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180831_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('manage_sme_admins', 'Can manage SME admins'), ('manage_teachers', 'Can manage teachers'), ('manage_pupils', 'Can manage pupils'), ('manage_energy_screen', 'Can manage energy screen'), ('view_energy_screen', 'Can view energy screen')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
