# Generated by Django 2.1.5 on 2019-01-09 11:50

from django.db import migrations

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_es_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManagerFromInLocationQuerySet()),
            ],
        ),
    ]
