# Generated by Django 2.1.5 on 2019-10-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0013_auto_20190425_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffPeakyPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('value', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='offpeakypoint',
            unique_together={('location', 'day')},
        ),
    ]
