# Generated by Django 2.1.5 on 2019-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offpeakypoint',
            name='value',
            field=models.FloatField(blank=True),
        ),
    ]
