# Generated by Django 2.1.5 on 2019-11-12 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0002_auto_20191031_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offpeakypoint',
            name='value',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
