# Generated by Django 2.1 on 2018-11-16 12:07

import django.db.models.deletion
import enumfields.fields
from django.db import migrations, models

import apps.energy_providers.providers.abstract
import apps.energy_tariffs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energy_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', enumfields.fields.EnumField(default='normal', enum=apps.energy_tariffs.models.TariffType, max_length=10)),
                ('meter_type', enumfields.fields.EnumField(db_index=True, enum=apps.energy_providers.providers.abstract.MeterType, max_length=20)),
                ('active_time_start', models.TimeField()),
                ('active_time_end', models.TimeField(blank=True, null=True)),
                ('active_date_start', models.DateField()),
                ('active_date_end', models.DateField(blank=True, null=True)),
                ('watt_hour_cost', models.FloatField()),
                ('daily_fixed_cost', models.FloatField()),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_providers.EnergyProviderAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
