# Generated by Django 2.1 on 2018-11-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytariff',
            name='monthly_fixed_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='energytariff',
            name='daily_fixed_cost',
            field=models.FloatField(default=0),
        ),
    ]
