# Generated by Django 2.1 on 2018-11-21 14:05

import enumfields.fields
from django.db import migrations

import apps.energy_tariffs.models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tariffs', '0002_auto_20181121_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytariff',
            name='type',
            field=enumfields.fields.EnumField(default='normal', enum=apps.energy_tariffs.models.TariffType, max_length=20),
        ),
    ]
