# Generated by Django 2.1 on 2018-11-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters', '0001_initial'),
        ('energy_tariffs', '0003_auto_20181121_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytariff',
            name='energy_meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy_meters.EnergyMeter'),
        ),
        migrations.AlterField(
            model_name='energytariff',
            name='provider_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='energy_providers.EnergyProviderAccount'),
        ),
    ]
