# Generated by Django 2.1.5 on 2019-02-27 14:47

import apps.resources.types
import apps.smart_things_devices.types
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_fix_long_term_history_time'),
        ('energy_tariffs', '0004_auto_20181127_1420'),
    ]
    operations = [
        migrations.AlterField(
            model_name='energytariff',
            name='energy_meter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                limit_choices_to=models.Q(
                    models.Q(
                        ('child_type', apps.resources.types.ResourceChildType('energy_meter')),
                        models.Q(
                            ('child_type', apps.resources.types.ResourceChildType('smart_things_sensor')),
                            ('smart_things_sensor__capability', apps.smart_things_devices.types.Capability('powerMeter'))
                        ),
                        _connector='OR'
                    )
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to='resources.Resource'),
        ),
        migrations.RenameField(
            model_name='energytariff',
            old_name='energy_meter',
            new_name='resource',
        ),
        migrations.AlterField(
            model_name='energytariff',
            name='provider_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy_providers.EnergyProviderAccount'),
        ),
    ]

