# Generated by Django 2.1.5 on 2019-03-18 10:51

import apps.resources.types
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tariffs', '0006_auto_20190304_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energytariff',
            name='resource',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('child_type', apps.resources.types.ResourceChildType('energy_meter')), ('child_type', apps.resources.types.ResourceChildType('smart_things_energy_meter')), _connector='OR')), null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Resource'),
        ),
    ]
