# Generated by Django 2.1.5 on 2019-07-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0003_auto_20190703_1058'),
        ('energy_tariffs', '0007_auto_20190318_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='energytariff',
            name='energy_meter_billing_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_tariffs', to='energy_meters_billing_info.EnergyMeterBillingInfo'),
        ),
    ]
