# Generated by Django 2.1.5 on 2019-12-18 13:10

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_meters_billing_info', '0012_remove_energymeterbillinginfo_annual_consumption'),
        ('energy_tariffs', '0008_energytariff_energy_meter_billing_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energytariff',
            name='energy_meter_billing_info',
        ),
        migrations.AddField(
            model_name='energytariff',
            name='active_days_in_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)]), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='energytariff',
            name='energy_meter_billing_info_consumption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_tariffs', to='energy_meters_billing_info.EnergyMeterBillingInfoConsumption'),
        ),
    ]
