# Generated by Django 2.1 on 2018-11-06 17:02

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import apps.energy_providers.models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0005_auto_20180831_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyProviderAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', enumfields.fields.EnumField(enum=apps.energy_providers.models.Provider, max_length=20)),
                ('credentials', encrypted_model_fields.fields.EncryptedCharField()),
                ('session_payload', encrypted_model_fields.fields.EncryptedCharField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='energyprovideraccount',
            unique_together={('location', 'name')},
        ),
    ]
