# Generated by Django 2.1 on 2018-11-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('historical_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermhistoricaldata',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_historical_data', to='resources.Resource'),
        ),
        migrations.AddField(
            model_name='detailedhistoricaldata',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_historical_data', to='resources.Resource'),
        ),
    ]
