# Generated by Django 2.1.5 on 2020-02-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0003_auto_20181127_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailedhistoricaldata',
            options={'verbose_name_plural': 'Detailed historical data'},
        ),
        migrations.AlterModelOptions(
            name='longtermhistoricaldata',
            options={'verbose_name_plural': 'Long term historical data'},
        ),
    ]
